### PR TITLE
Updates Completed

### PR DESCRIPTION
**Pull request by khamseen**
Everything seems to be working out now.
I've added a new face to each of the pane sections in Blender, renamed their original materials to the subtypeIDs off the CCW materials used, added and assigned new materials for the CW versions to the new faces.
Fixed up some sloped windows which had their glass not fitting to the edge of the cube correctly.
Changed all transparent material settings because the way the game handles transparent materials has changed so much, I think I've got them looking ok though and more like they used to.
Added material overrides for vanilla windows so any leftovers match the mod windows appearance better.
Added GMenu scroll options to all base variants, flat, flat inverted, sides etc.
I think that's pretty much everything.

### CODE REVIEW

**Comment by JakenVeina** [comment]
Everything looks good except for the 1x1 Slope Inverted window. It looks like maybe the wrong texture got mapped somewhere. All the variations (that should have it) are missing the dirt lines on the right-hand and bottom edges. You're probably more equipped to find the issue quickly than I am, but if you have trouble, I can dig into it further. The non-inverted variants all have the right textures, as far as I can tell.

**Comment by khamseen** [comment]
Woops, don't know how I missed that. I'll take a look when I get home and re-upload them once they're fixed.

**Comment by khamseen** [comment]
I've had a look on my end and I don't see the missing textures you're talking about.
I do know though that the dirt can be very hard to see at times now, especially if an armour block is on the other side. The vanilla dirt has the same issue.
To check I edited the transparency <w> in transparent materials all the way up to 1 so it was completely visible and on my end they all had their dirt showing.

**Comment by JakenVeina** [comment]
What settings are you referring to? I raised all the "W" settings in "TransparentMaterials.sbc" up to 1 and got this.

https://steamuserimages-a.akamaihd.net/ugc/847095917493822863/D29E8AC6605498E1149406277FC0801D3FF0E19B/

Which is rather bizarre. The dirt texture is clearly there on all sides, but it seems to be more..... profound on the top and left? Is that texture maybe being duplicated, so it gets darker after layering together?

This should basically be a fresh pull from the Repo, but if you have trouble duplicating this, I say we should both wipe and re-pull again.

**Comment by khamseen** [comment]
Oh wow, that looks odd...
Let me recheck everything on my end again just to confirm. I'll try wiping my repository and re-uploading once I've confirmed everything to be ok just in case I did manage to mess something up. Then I'll cancel the pull request and issue a new one.

**Comment by JakenVeina** [comment]
No, no, don't cancel the PR. That's silly. If you don't have the same thing on your end, we just need to find which files are different. Unless it's somehow the save...

**Comment by khamseen** [comment]
I've now been somewhat able to recreate it on my end. It appears to be shadow related somehow... I'm still not sure on the 'how' of it.
Here it is in direct sunlight
https://i.imgur.com/kZ121tp.jpg

Here it is when I rotate my grid round a bit so it's got a shadow cast on it
https://i.imgur.com/hMOTNbv.jpg

I think it's most likely texture related, but I'm not 100% on that yet. I'll play around and see if I did something wrong there.

**Comment by khamseen** [comment]
OK, somewhat narrowed it down. Disabling <CanBeAffectedByOtherLights> stops it happening, but the vanilla window definitions have that enabled and don't suffer this issue so I'll try and figure out what's different about their textures.

**Comment by khamseen** [comment]
*Damn auto removal, disabling "CanBeAffectedByOtherLights"

**Comment by khamseen** [comment]
I've tracked the cause down, I'd used vanilla settings for the new "ShadowMultiplier" settings but they don't react the way they do for vanilla glass and that's why they're going like that. I'm making some final adjustments to the transparentmaterials file and I'll push it to the repo when I'm finished.

**Comment by khamseen** [comment]
OK man, I've pushed an updated transparentmaterials file to my repo. Check it out and see how you get on.

**Comment by JakenVeina** [comment]
I don't see any new files added to the project in the commits. Is that correct? Can you think of anything else that might require change to the rebuild_package.bat script?

**Comment by khamseen** [comment]
There was one new dds added to the particles folder, the 4Edge_0Corner variant. 
Checked the .bat script though and I think it covers everything so it shouldn't need any changes.

**Pull request merged**
